version: 0.2

phases:
  build:
    commands:
      - echo Build Starting
      - mvn clean package
    post_build:
      commands:
        - echo Build completed!
artifacts:
  files:
    - target/tusucoreapi-0.0.1-SNAPSHOT.jar
  discard-paths: yes